GoodAnswer.create!([
  {question_id: 1, wording: "try", reason: "Not a reserved word"},
  {question_id: 1, wording: "goto", reason: "Not a reserved word"},
  {question_id: 2, wording: "1", reason: "a is defined and will be returned"},
  {question_id: 3, wording: "2", reason: "Returns the number of key-value pairs"},
  {question_id: 4, wording: "Current system time + a day later ", reason: "Time#+ method adds some number of seconds to time "},
  {question_id: 5, wording: "_365", reason: "Start with underscore"},
  {question_id: 5, wording: "switch", reason: "Switch is not a reserved word"},
  {question_id: 5, wording: "z", reason: "Start with lowercase charater"},
  {question_id: 6, wording: "1 0, 2 1", reason: "A  Range  object  represents  an  interval  that  is  a  group  of  numbers  that  includes  all  integer  number    between  the  beginning  and  the  end. You  can  use  ranges  by  means  of  the    ..  and  ...  operators.Also, i is the value and j the index."},
  {question_id: 7, wording: "[100,98,96,94,92,90]", reason: "Downto iterates from a large number to min number.\r\n"},
  {question_id: 8, wording: "collect", reason: "Returns a new array with the results of running block once for every element."},
  {question_id: 8, wording: "map", reason: "Returns a new array with the results of running block once for every element."},
  {question_id: 9, wording: "uby on", reason: "Returns  a  copy  of  string  with  all  characters  in  the  intersection  of  its  arguments  deleted."},
  {question_id: 10, wording: "Replace the first <<EOF with <<-­EOF.", reason: "You  can  omit  the  dash  \r\nand  just  write  <<  of  the  identifier  -­‐  if  you  do  this,  your  terminating  se\r\n-­‐\r\nquence  must  be  at  the  begging  of  the  line."},
  {question_id: 10, wording: "Remove the whitespace in front of the last EOF.", reason: "You  can  omit  the  dash  \r\nand  just  write  <<  of  the  identifier  -­‐  if  you  do  this,  your  terminating  se\r\n-­‐\r\nquence  must  be  at  the  begging  of  the  line."},
  {question_id: 11, wording: "clear", reason: "Removes all elements from self."},
  {question_id: 12, wording: "a[0..2]", reason: "Index 0 to 2"},
  {question_id: 12, wording: "a.slice(0,3)", reason: "Index 0 to 2"},
  {question_id: 13, wording: "\"RubyAssociation\" ", reason: "Remove any trailing newline or carriage return characters"},
  {question_id: 14, wording: "\"RubyAssociation\"", reason: "Remove any trailing newline or carriage return characters"},
  {question_id: 15, wording: "Positions ios to the beginning of input, resetting lineno to zero.", reason: "No reason"},
  {question_id: 16, wording: "‐", reason: "Difference"},
  {question_id: 17, wording: "[1,2,3,4,5,6]", reason: "sort returns a new array created by sorting self"},
  {question_id: 18, wording: "Hello", reason: "Word start with h or c and ends with o."},
  {question_id: 19, wording: "A warning appears since Greeting is a constant but \"Hi Ruby\" is displayed", reason: "The Ruby doesn’t enforce the constancy of constants, it does issue a only \r\nwarning message if a user change the value of a constant."},
  {question_id: 20, wording: "\"ruby/exam/silver\"", reason: "join returns a new string formed by joining the strings using File::SEPARATOR.(/)"},
  {question_id: 21, wording: "50,10", reason: "The super has a special meaning in a method overriding. It invokes a methods\r\nwith the same name as the current one, in it’s superclass of the current class.(self)"},
  {question_id: 22, wording: "\"test code\"", reason: "Returns a new string with the substring."},
  {question_id: 23, wording: "UTF-­8", reason: "UTF-­8 is the default character encoding of Ruby 2.0 or later."},
  {question_id: 24, wording: "p cc.contain?(\"nz\")", reason: "Doesn't exist"},
  {question_id: 25, wording: "String - Object - Object - Foo", reason: "superclass returns the superclass of class, or nil.\r\nObject is the default parent of all classes in Ruby"},
  {question_id: 26, wording: "(1)scan (2)/\\w+/", reason: "Scan returns everything that the Regular expression matches"},
  {question_id: 27, wording: "Returns a string containing the character represented by the int‘s value according to encoding.", reason: "No reason"},
  {question_id: 27, wording: "an Error has occurred if wrong encoding name is given.", reason: "No reason"},
  {question_id: 28, wording: "(1)begin, (2) rescue indexError", reason: "To do exception handling, we enclose the code that could raise an exception in a begin-end block and use one or more rescue clauses to tell Ruby the types of exceptions we want to handle."},
  {question_id: 29, wording: "[1,4]", reason: "&& operator :\r\nif lefthand operand is nil or false, then returns that value. In other word,\r\nrighthand operand is ignored.\r\n\r\n|| operator\r\nFirst, it evaluate its lefthand operand, and if this is any value other than\r\nnil or false, it returns that value. if it’s nil or false , it evaluates its\r\nrighthand operand and returns that value."},
  {question_id: 30, wording: "\"foofoofoofoo\"", reason: "High precedence operation(**) happen before low precedence operation(*)"},
  {question_id: 31, wording: "679", reason: "The parameter(\"0-­58-­\") means that remove a 0 to 5, 8 and -­ from string."},
  {question_id: 32, wording: "How are you?", reason: "You can always re-­‐open the class and add or overwrite methods to an existing class."},
  {question_id: 33, wording: "(1)split(\",\"), (2)join(\"\\n\")", reason: "split returns an array of substrings.\r\nJoin returns a string created by converting each element of the array to a string."},
  {question_id: 34, wording: "89", reason: "Combines all elements of enum by applying a binary operation, specified by a block or a symbol that names a method or operator."},
  {question_id: 35, wording: "@@num", reason: "class variable"},
  {question_id: 36, wording: "10", reason: "A leading zero in an integer literal indicates 'octal-mode' in Ruby"},
  {question_id: 37, wording: "[\"a\",\"b\",\"c\",\"d\",\"e\",\"f\"]", reason: "Returns an array containing the items in enum."},
  {question_id: 38, wording: "Hello", reason: "If the value is false the “then” expression is executed.\r\nIn Boolean context, false and nil are false."},
  {question_id: 39, wording: "Ruby opens foo.txt in read only mode", reason: "Without specified mode, open on read only."},
  {question_id: 40, wording: "5", reason: "Passes each entry in enum to block. Returns the first for which block is not false."},
  {question_id: 41, wording: "10,10", reason: "0xA is hexadecimal for 10 and 012 is 10 on base 8"},
  {question_id: 42, wording: "333-­4421", reason: "[0-­‐9]{3} require 3 digit,\r\n- require \"-\",\r\n­[0­‐9]{4} require 4 digit"},
  {question_id: 43, wording: "non ascii character detected : ルビー, non ascii character detected : ЛУЧШИЙ ДРУГ ПРОГРАММИСТА", reason: "raise will be called then rescue"},
  {question_id: 44, wording: "capital = {\"Sweden\" = \"Stockholm\", \"Norway\" = \"Oslo\", \"Finland\" = \"Helsinki\"}", reason: "SyntaxError"},
  {question_id: 45, wording: "gets", reason: "Reads the next “line'' from the I/O stream"},
  {question_id: 45, wording: "readline", reason: "Reads a line as with IO#gets"}
])
